language: objective-c
osx_image: xcode9.2
branches:
  only:
    - master

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  podfile: Example/Podfile
  - gem install cocoapods  
  - pod install --project-directory=Example

# cache: cocoapods
# podfile: Example/Podfile

script:
  - set -o pipefail
  - xcodebuild -workspace Example/AXReachability.xcworkspace -scheme AXReachability-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - pod lib lint
