language: objective-c
osx_image: xcode9.2
branches:
  only:
    - master
before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - pod install --project-directory=Example

# cache: cocoapods
# podfile: Example/Podfile


script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/AXReachability.xcworkspace -scheme AXReachability-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
